# Experimental open-source research release under Apache-2.0; NVIDIA providers remain external.
set(CPACK_PACKAGE_NAME "vramz")
set(CPACK_PACKAGE_VENDOR "VRAMZ project")
set(CPACK_PACKAGE_VERSION "1.0.0-rc1")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Experimental GPU-resident compressed-memory runtime (research preview)")
set(CPACK_GENERATOR "DEB;TGZ")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_DEBIAN_PACKAGE_VERSION "1.0.0~rc1")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Rami Nezer / VRAMZ project")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.38), libstdc++6 (>= 13), libgcc-s1, python3 (>= 3.11), binutils")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS OFF)
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
include(CPack)
