function(vramz_enable_sanitizer target)
    if(VRAMZ_SANITIZER STREQUAL "none")
        return()
    elseif(VRAMZ_SANITIZER STREQUAL "address")
        set(flags -fsanitize=address -fno-omit-frame-pointer)
    elseif(VRAMZ_SANITIZER STREQUAL "undefined")
        set(flags -fsanitize=undefined -fno-omit-frame-pointer)
    elseif(VRAMZ_SANITIZER STREQUAL "thread")
        set(flags -fsanitize=thread -fno-omit-frame-pointer)
    elseif(VRAMZ_SANITIZER STREQUAL "leak")
        set(flags -fsanitize=leak -fno-omit-frame-pointer)
    else()
        message(FATAL_ERROR "Unknown VRAMZ_SANITIZER=${VRAMZ_SANITIZER}")
    endif()

    target_compile_options(${target} PRIVATE ${flags})
    target_link_options(${target} PRIVATE ${flags})
endfunction()
